### ISSUE TITLE
load reorientation matrix in some brains does not apply correctly

### ISSUE THREAD

**Issue by katjaq** [r03ert0/reorient#2]
reorientation matrix created with fsleyes in some brains works as expected, but in others does not apply correctly: S-I and A-P seem to be confused, as for instance in this example.
<img width="635" alt="screen shot 2018-01-17 at 14 19 20" src="https://user-images.githubusercontent.com/6297454/35044631-714391b6-fb91-11e7-80e0-c71399a29162.png">
The two matrices from the data here: first fsleyes' matrix, second reorient's matrix
0.2369912408236008 -0.1213331651480376 -0.07008762029479479 -39.18383135547021
-0.1143165094336471 -0.24668841602199848 0.04199982435366864 81.41957030499984
0.07994919843735564 0.006933637046685351 0.26781288412480403 -64.48064838383002
0 0 0 1.0000000000000002

-0.8464815339 0.4458264438 0.2910460356 128.9460969794
0.3120553519 -0.0274717284 0.9496666581 15.5981561966
0.4313820466 0.8946977625 -0.1158682170 -51.8527407005
0.0000000000 0.0000000000 0.0000000000 1.0000000000

**Comment by r03ert0** [comment]
the problem was that matrices loaded in FSL are appended to the existing matrix encoded in the MRI header, but in `reorient` the encoded matrix is replaced with the loaded one. Commit 6f346c7 adds a button to allow to append a matrix instead of replacing, and fixes the bug.
